# Generated by Django 3.1 on 2020-11-08 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('displayJSON', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myTable',
            fields=[
                ('userId', models.PositiveIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='my_table',
        ),
    ]
